spring:
  application:
    name: javazolotaya

  datasource:
    url: jdbc:postgresql://localhost:5432/itmo_cities
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

  springdoc:
    swagger-ui:
      path: /swagger-ui.html

  liquibase:
    clear-checksums: true
    change-log: classpath:db/changelog/changelog-master.yaml

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

fibonacci:
  useCache: false

logging:
    level:
      root: INFO
      org.springdoc: DEBUG
      org.springframework.web: DEBUG
      org.springframework.boot.autoconfigure: DEBUG
      org.hibernate: WARN